# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_gridworld_wrappers", use_symbols = TRUE, package_name = "gridworld")

#' @docType package
#' @usage NULL
#' @useDynLib gridworld, .registration = TRUE
NULL

#' Does value iteration
#' @export
value_iteration <- function(reward, obstacles, wind, beta) .Call(wrap__value_iteration, reward, obstacles, wind, beta)

#' Generates trajectories
generate_trajs <- function(policy, obstacles, wind, n_trajectories) .Call(wrap__generate_trajs, policy, obstacles, wind, n_trajectories)

